name: Create Exoscale Infrastructure

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Abgabe_2_260513

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize OpenTofu
        run: tofu init

      - name: Plan infrastructure
        run: tofu plan
        env:
          TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
          TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

      - name: Create infrastructure
        run: tofu apply -auto-approve
        env:
          TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
          TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}
